openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /likes/liked-list:
    get:
      operationId: liked_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - likes
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedRatedProfileList'
          description: ''
  /likes/likes-list:
    get:
      operationId: likes_list
      tags:
      - likes
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LikesList'
          description: ''
  /likes/pair-list:
    get:
      operationId: pair_list
      tags:
      - likes
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PairList'
          description: ''
  /likes/rate-profile:
    post:
      operationId: rate_profile
      tags:
      - likes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RateProfile'
        required: true
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RateProfile'
          description: ''
  /profiles/create-profile:
    post:
      operationId: create_profile
      tags:
      - profiles
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CurrentProfile'
        required: true
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentProfile'
          description: ''
  /profiles/current-profile:
    get:
      operationId: current_profile
      tags:
      - profiles
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentProfile'
          description: ''
  /profiles/profile-details/{id}:
    get:
      operationId: profile_details
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - profiles
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileDetails'
          description: ''
  /profiles/profile-list:
    get:
      operationId: profile_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - profiles
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedProfileList'
          description: ''
  /users/current-user:
    get:
      operationId: current_user
      tags:
      - users
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /users/force-token:
    get:
      operationId: force_token
      parameters:
      - in: query
        name: profileId
        schema:
          type: integer
      - in: query
        name: userId
        schema:
          type: integer
      tags:
      - users
      security:
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /users/refresh-token:
    post:
      operationId: refresh_token
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
components:
  schemas:
    CurrentProfile:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          maxLength: 32
        age:
          type: integer
        gender:
          enum:
          - male
          - maleTrans
          - female
          - femaleTrans
          - nonBinary
          type: string
        femAvatar:
          type: boolean
        setup:
          enum:
          - quest
          - pcvr
          - fbt
          type: string
        role:
          enum:
          - sub
          - dom
          - switch
          type: string
        mute:
          type: boolean
        furry:
          type: boolean
        verified:
          type: boolean
        startHour:
          type: integer
          maximum: 2147483647
          minimum: 0
          nullable: true
        endHour:
          type: integer
          maximum: 2147483647
          minimum: 0
          nullable: true
        weekDays:
          type: array
          items:
            enum:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            type: integer
            minimum: 0
            maximum: 32767
          nullable: true
        description:
          type: string
          nullable: true
          maxLength: 512
        preferences:
          $ref: '#/components/schemas/Preferences'
        birthDate:
          type: string
          format: date
      required:
      - age
      - birthDate
      - femAvatar
      - furry
      - gender
      - id
      - mute
      - preferences
      - role
      - setup
      - username
    LikesList:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/RatedProfile'
        likesBadge:
          type: integer
      required:
      - likesBadge
      - results
    PaginatedProfileList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/Profile'
    PaginatedRatedProfileList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/RatedProfile'
    Pair:
      type: object
      description: Flatens the specified related objects in this representation
      properties:
        id:
          type: integer
          readOnly: true
        date:
          type: string
          format: date-time
          readOnly: true
      required:
      - date
      - id
    PairList:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/Pair'
        pairsBadge:
          type: integer
      required:
      - pairsBadge
      - results
    Preferences:
      type: object
      properties:
        gender:
          type: array
          items:
            enum:
            - male
            - maleTrans
            - female
            - femaleTrans
            - nonBinary
            type: string
        femAvatar:
          enum:
          - 'true'
          - 'false'
          - any
          type: string
        ageMin:
          type: integer
          maximum: 32767
          minimum: 0
        ageMax:
          type: integer
          maximum: 32767
          minimum: 0
          nullable: true
        setup:
          type: array
          items:
            enum:
            - quest
            - pcvr
            - fbt
            type: string
        role:
          type: array
          items:
            enum:
            - sub
            - dom
            - switch
            type: string
        mute:
          enum:
          - 'true'
          - 'false'
          - any
          type: string
        furry:
          enum:
          - 'true'
          - 'false'
          - any
          type: string
      required:
      - ageMin
      - femAvatar
      - furry
      - gender
      - mute
      - role
      - setup
    Profile:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          maxLength: 32
        age:
          type: integer
        gender:
          enum:
          - male
          - maleTrans
          - female
          - femaleTrans
          - nonBinary
          type: string
        femAvatar:
          type: boolean
        setup:
          enum:
          - quest
          - pcvr
          - fbt
          type: string
        role:
          enum:
          - sub
          - dom
          - switch
          type: string
        mute:
          type: boolean
        furry:
          type: boolean
        verified:
          type: boolean
      required:
      - age
      - femAvatar
      - furry
      - gender
      - id
      - mute
      - role
      - setup
      - username
    ProfileDetails:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          maxLength: 32
        age:
          type: integer
        gender:
          enum:
          - male
          - maleTrans
          - female
          - femaleTrans
          - nonBinary
          type: string
        femAvatar:
          type: boolean
        setup:
          enum:
          - quest
          - pcvr
          - fbt
          type: string
        role:
          enum:
          - sub
          - dom
          - switch
          type: string
        mute:
          type: boolean
        furry:
          type: boolean
        verified:
          type: boolean
        startHour:
          type: integer
          maximum: 2147483647
          minimum: 0
          nullable: true
        endHour:
          type: integer
          maximum: 2147483647
          minimum: 0
          nullable: true
        weekDays:
          type: array
          items:
            enum:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            type: integer
            minimum: 0
            maximum: 32767
          nullable: true
        description:
          type: string
          nullable: true
          maxLength: 512
        preferences:
          $ref: '#/components/schemas/Preferences'
      required:
      - age
      - femAvatar
      - furry
      - gender
      - id
      - mute
      - preferences
      - role
      - setup
      - username
    RateProfile:
      type: object
      properties:
        profileId:
          type: integer
        liked:
          type: boolean
      required:
      - liked
      - profileId
    RatedProfile:
      type: object
      properties:
        liked:
          type: string
          readOnly: true
        likes:
          type: string
          readOnly: true
        date:
          type: string
          format: date-time
        profile:
          type: integer
      required:
      - liked
      - likes
      - profile
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        isStaff:
          type: boolean
        discordUsername:
          type: string
          maxLength: 32
        discordDiscriminator:
          type: string
          maxLength: 4
        hasProfile:
          type: boolean
      required:
      - discordDiscriminator
      - discordUsername
      - hasProfile
      - id
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
