# Generated by Django 3.1.13 on 2021-11-24 13:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Preferences",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            choices=[
                                (1, "Male"),
                                (2, "Male Trans"),
                                (5, "Female"),
                                (6, "Female Trans"),
                                (9, "Other"),
                            ]
                        ),
                        size=None,
                    ),
                ),
                (
                    "role",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            choices=[(1, "Sub"), (2, "Dom"), (3, "Switch")]
                        ),
                        size=3,
                    ),
                ),
                (
                    "setup",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            choices=[(1, "Quest"), (2, "Pcvr"), (3, "Fbt")]
                        ),
                        size=3,
                    ),
                ),
                (
                    "feminine_avatar",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Yes"), (2, "No"), (3, "Both")]
                    ),
                ),
                (
                    "furry",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Yes"), (2, "No"), (3, "Both")]
                    ),
                ),
                ("age_min", models.PositiveSmallIntegerField()),
                ("age_max", models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birth_date", models.DateField()),
                (
                    "gender",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Male"),
                            (2, "Male Trans"),
                            (5, "Female"),
                            (6, "Female Trans"),
                            (9, "Other"),
                        ]
                    ),
                ),
                ("other_gender", models.CharField(max_length=32, null=True)),
                (
                    "attracted_gender",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            choices=[
                                (1, "Male"),
                                (2, "Male Trans"),
                                (5, "Female"),
                                (6, "Female Trans"),
                                (9, "Other"),
                            ]
                        ),
                        size=5,
                    ),
                ),
                (
                    "role",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Sub"), (2, "Dom"), (3, "Switch")]
                    ),
                ),
                (
                    "setup",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Quest"), (2, "Pcvr"), (3, "Fbt")]
                    ),
                ),
                ("feminine_avatar", models.BooleanField()),
                ("furry", models.BooleanField()),
                ("username", models.CharField(max_length=32, null=True)),
                ("description", models.CharField(max_length=512, null=True)),
                ("start_hour", models.PositiveIntegerField()),
                ("end_hour", models.PositiveIntegerField()),
                (
                    "week_days",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            choices=[
                                (1, "Monday"),
                                (2, "Tuesday"),
                                (3, "Wednesday"),
                                (4, "Thursday"),
                                (5, "Friday"),
                                (6, "Saturday"),
                                (7, "Sunday"),
                            ]
                        ),
                        size=7,
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("visible", models.BooleanField(default=True)),
            ],
        ),
    ]
