# Generated by Django 3.1.13 on 2021-12-16 21:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LikedProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skipped", models.BooleanField(default=False)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "unique_together": {("author", "profile")},
            },
        ),
        migrations.CreateModel(
            name="Pair",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contacted1", models.BooleanField(default=False)),
                ("contacted2", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("profile1", "profile2")},
            },
        ),
        migrations.CreateModel(
            name="SkippedProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "unique_together": {("author", "profile")},
            },
        ),
    ]
