# Generated by Django 3.1.13 on 2022-01-04 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("likes", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skippedprofile",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skipped_profiles",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="skippedprofile",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skips",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="pair",
            name="profile1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pair1",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="pair",
            name="profile2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pair2",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="likedprofile",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_profiles",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="likedprofile",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="profiles.profile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="skippedprofile",
            unique_together={("author", "profile")},
        ),
        migrations.AlterUniqueTogether(
            name="pair",
            unique_together={("profile1", "profile2")},
        ),
        migrations.AlterUniqueTogether(
            name="likedprofile",
            unique_together={("author", "profile")},
        ),
    ]
