/**
 * Generated by orval v6.6.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.0
 */
export type ForceTokenParams = { profileId?: number; userId?: number }

export type ProfileListParams = { limit?: number; offset?: number }

export type ProfileFeedParams = { limit?: number; offset?: number }

export type LikedListParams = { limit?: number; offset?: number }

export interface User {
  readonly id: number
  isStaff?: boolean
  discordUsername: string
  discordDiscriminator: string
  hasProfile: boolean
}

export interface TokenRefresh {
  readonly access: string
  refresh: string
}

export interface RatedProfileDeep {
  readonly liked: boolean
  readonly likes: boolean
  date?: string
  profile: Profile
}

export interface RatedProfile {
  liked: boolean
  date?: string
}

export interface RateProfile {
  profileId: number
  liked: boolean
}

export interface ProfileImage {
  image: string
  order?: number
}

export type ProfileFormSetup = "quest" | "pcvr" | "fbt"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfileFormSetup = {
  quest: "quest" as ProfileFormSetup,
  pcvr: "pcvr" as ProfileFormSetup,
  fbt: "fbt" as ProfileFormSetup,
}

export type ProfileFormRole = "sub" | "dom" | "switch"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfileFormRole = {
  sub: "sub" as ProfileFormRole,
  dom: "dom" as ProfileFormRole,
  switch: "switch" as ProfileFormRole,
}

export type ProfileFormGender = "male" | "maleTrans" | "female" | "femaleTrans" | "nonBinary"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfileFormGender = {
  male: "male" as ProfileFormGender,
  maleTrans: "maleTrans" as ProfileFormGender,
  female: "female" as ProfileFormGender,
  femaleTrans: "femaleTrans" as ProfileFormGender,
  nonBinary: "nonBinary" as ProfileFormGender,
}

/**
 * Adds nested create feature
 */
export interface ProfileForm {
  femAvatar: boolean
  gender: ProfileFormGender
  trans: boolean
  furry: boolean
  mute: boolean
  role: ProfileFormRole
  setup: ProfileFormSetup
}

export type ProfileDetailsWeekDaysItem = 1 | 2 | 3 | 4 | 5 | 6 | 7

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfileDetailsWeekDaysItem = {
  NUMBER_1: 1 as ProfileDetailsWeekDaysItem,
  NUMBER_2: 2 as ProfileDetailsWeekDaysItem,
  NUMBER_3: 3 as ProfileDetailsWeekDaysItem,
  NUMBER_4: 4 as ProfileDetailsWeekDaysItem,
  NUMBER_5: 5 as ProfileDetailsWeekDaysItem,
  NUMBER_6: 6 as ProfileDetailsWeekDaysItem,
  NUMBER_7: 7 as ProfileDetailsWeekDaysItem,
}

export type ProfileDetailsRole = "sub" | "dom" | "switch"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfileDetailsRole = {
  sub: "sub" as ProfileDetailsRole,
  dom: "dom" as ProfileDetailsRole,
  switch: "switch" as ProfileDetailsRole,
}

export type ProfileDetailsSetup = "quest" | "pcvr" | "fbt"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfileDetailsSetup = {
  quest: "quest" as ProfileDetailsSetup,
  pcvr: "pcvr" as ProfileDetailsSetup,
  fbt: "fbt" as ProfileDetailsSetup,
}

export type ProfileDetailsGender = "male" | "maleTrans" | "female" | "femaleTrans" | "nonBinary"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfileDetailsGender = {
  male: "male" as ProfileDetailsGender,
  maleTrans: "maleTrans" as ProfileDetailsGender,
  female: "female" as ProfileDetailsGender,
  femaleTrans: "femaleTrans" as ProfileDetailsGender,
  nonBinary: "nonBinary" as ProfileDetailsGender,
}

export interface ProfileDetails {
  readonly id: number
  username: string
  age: number
  gender: ProfileDetailsGender
  femAvatar: boolean
  setup: ProfileDetailsSetup
  role: ProfileDetailsRole
  mute: boolean
  furry: boolean
  verified?: boolean
  thumbnail?: string | null
  startHour?: number | null
  endHour?: number | null
  weekDays?: ProfileDetailsWeekDaysItem[] | null
  description?: string | null
  preferences: Preferences
  images: ProfileImage[]
}

export interface ProfileFeed {
  profile: ProfileDetails
  ratedProfile: RatedProfile
}

export type ProfileRole = "sub" | "dom" | "switch"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfileRole = {
  sub: "sub" as ProfileRole,
  dom: "dom" as ProfileRole,
  switch: "switch" as ProfileRole,
}

export type ProfileSetup = "quest" | "pcvr" | "fbt"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfileSetup = {
  quest: "quest" as ProfileSetup,
  pcvr: "pcvr" as ProfileSetup,
  fbt: "fbt" as ProfileSetup,
}

export type ProfileGender = "male" | "maleTrans" | "female" | "femaleTrans" | "nonBinary"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfileGender = {
  male: "male" as ProfileGender,
  maleTrans: "maleTrans" as ProfileGender,
  female: "female" as ProfileGender,
  femaleTrans: "femaleTrans" as ProfileGender,
  nonBinary: "nonBinary" as ProfileGender,
}

export interface Profile {
  readonly id: number
  username: string
  age: number
  gender: ProfileGender
  femAvatar: boolean
  setup: ProfileSetup
  role: ProfileRole
  mute: boolean
  furry: boolean
  verified?: boolean
  thumbnail?: string | null
}

export type PreferencesFormSetupItem = "quest" | "pcvr" | "fbt"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreferencesFormSetupItem = {
  quest: "quest" as PreferencesFormSetupItem,
  pcvr: "pcvr" as PreferencesFormSetupItem,
  fbt: "fbt" as PreferencesFormSetupItem,
}

export type PreferencesFormRoleItem = "sub" | "dom" | "switch"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreferencesFormRoleItem = {
  sub: "sub" as PreferencesFormRoleItem,
  dom: "dom" as PreferencesFormRoleItem,
  switch: "switch" as PreferencesFormRoleItem,
}

export type PreferencesFormMute = "true" | "false" | "any"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreferencesFormMute = {
  true: "true" as PreferencesFormMute,
  false: "false" as PreferencesFormMute,
  any: "any" as PreferencesFormMute,
}

export type PreferencesFormFurry = "true" | "false" | "any"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreferencesFormFurry = {
  true: "true" as PreferencesFormFurry,
  false: "false" as PreferencesFormFurry,
  any: "any" as PreferencesFormFurry,
}

export type PreferencesFormGenderItem =
  | "male"
  | "maleTrans"
  | "female"
  | "femaleTrans"
  | "nonBinary"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreferencesFormGenderItem = {
  male: "male" as PreferencesFormGenderItem,
  maleTrans: "maleTrans" as PreferencesFormGenderItem,
  female: "female" as PreferencesFormGenderItem,
  femaleTrans: "femaleTrans" as PreferencesFormGenderItem,
  nonBinary: "nonBinary" as PreferencesFormGenderItem,
}

export type PreferencesFormFemAvatar = "true" | "false" | "any"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreferencesFormFemAvatar = {
  true: "true" as PreferencesFormFemAvatar,
  false: "false" as PreferencesFormFemAvatar,
  any: "any" as PreferencesFormFemAvatar,
}

export interface PreferencesForm {
  ageMax: number
  ageMin: number
  femAvatar: PreferencesFormFemAvatar
  gender: PreferencesFormGenderItem[]
  furry: PreferencesFormFurry
  mute: PreferencesFormMute
  role: PreferencesFormRoleItem[]
  setup: PreferencesFormSetupItem[]
}

export type PreferencesFurry = "true" | "false" | "any"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreferencesFurry = {
  true: "true" as PreferencesFurry,
  false: "false" as PreferencesFurry,
  any: "any" as PreferencesFurry,
}

export type PreferencesMute = "true" | "false" | "any"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreferencesMute = {
  true: "true" as PreferencesMute,
  false: "false" as PreferencesMute,
  any: "any" as PreferencesMute,
}

export type PreferencesRoleItem = "sub" | "dom" | "switch"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreferencesRoleItem = {
  sub: "sub" as PreferencesRoleItem,
  dom: "dom" as PreferencesRoleItem,
  switch: "switch" as PreferencesRoleItem,
}

export type PreferencesSetupItem = "quest" | "pcvr" | "fbt"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreferencesSetupItem = {
  quest: "quest" as PreferencesSetupItem,
  pcvr: "pcvr" as PreferencesSetupItem,
  fbt: "fbt" as PreferencesSetupItem,
}

export type PreferencesFemAvatar = "true" | "false" | "any"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreferencesFemAvatar = {
  true: "true" as PreferencesFemAvatar,
  false: "false" as PreferencesFemAvatar,
  any: "any" as PreferencesFemAvatar,
}

export type PreferencesGenderItem = "male" | "maleTrans" | "female" | "femaleTrans" | "nonBinary"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PreferencesGenderItem = {
  male: "male" as PreferencesGenderItem,
  maleTrans: "maleTrans" as PreferencesGenderItem,
  female: "female" as PreferencesGenderItem,
  femaleTrans: "femaleTrans" as PreferencesGenderItem,
  nonBinary: "nonBinary" as PreferencesGenderItem,
}

export interface Preferences {
  gender: PreferencesGenderItem[]
  femAvatar: PreferencesFemAvatar
  ageMin: number
  ageMax: number
  setup: PreferencesSetupItem[]
  role: PreferencesRoleItem[]
  mute: PreferencesMute
  furry: PreferencesFurry
}

export interface Pair {
  readonly id: number
  readonly date: string
  profile: Profile
}

export interface PairList {
  results: Pair[]
  pairsBadge: number
}

export interface PaginatedRatedProfileDeepList {
  count?: number
  next?: string | null
  previous?: string | null
  results?: RatedProfileDeep[]
}

export interface PaginatedProfileList {
  count?: number
  next?: string | null
  previous?: string | null
  results?: Profile[]
}

export interface PaginatedProfileFeedList {
  count?: number
  next?: string | null
  previous?: string | null
  results?: ProfileFeed[]
}

export interface LikesList {
  results: RatedProfileDeep[]
  likesBadge: number
}

export type CurrentProfileWeekDaysItem = 1 | 2 | 3 | 4 | 5 | 6 | 7

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CurrentProfileWeekDaysItem = {
  NUMBER_1: 1 as CurrentProfileWeekDaysItem,
  NUMBER_2: 2 as CurrentProfileWeekDaysItem,
  NUMBER_3: 3 as CurrentProfileWeekDaysItem,
  NUMBER_4: 4 as CurrentProfileWeekDaysItem,
  NUMBER_5: 5 as CurrentProfileWeekDaysItem,
  NUMBER_6: 6 as CurrentProfileWeekDaysItem,
  NUMBER_7: 7 as CurrentProfileWeekDaysItem,
}

export type CurrentProfileRole = "sub" | "dom" | "switch"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CurrentProfileRole = {
  sub: "sub" as CurrentProfileRole,
  dom: "dom" as CurrentProfileRole,
  switch: "switch" as CurrentProfileRole,
}

export type CurrentProfileSetup = "quest" | "pcvr" | "fbt"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CurrentProfileSetup = {
  quest: "quest" as CurrentProfileSetup,
  pcvr: "pcvr" as CurrentProfileSetup,
  fbt: "fbt" as CurrentProfileSetup,
}

export type CurrentProfileGender = "male" | "female" | "nonBinary"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CurrentProfileGender = {
  male: "male" as CurrentProfileGender,
  female: "female" as CurrentProfileGender,
  nonBinary: "nonBinary" as CurrentProfileGender,
}

export interface CurrentProfile {
  readonly id: number
  username: string
  age: number
  readonly gender: CurrentProfileGender
  femAvatar: boolean
  setup: CurrentProfileSetup
  role: CurrentProfileRole
  mute: boolean
  furry: boolean
  verified?: boolean
  thumbnail?: string | null
  startHour?: number | null
  endHour?: number | null
  weekDays?: CurrentProfileWeekDaysItem[] | null
  description?: string | null
  preferences: Preferences
  images: ProfileImage[]
  readonly birthMonth: number
  readonly birthYear: number
  readonly trans: boolean
}

export type CreateProfileFormSetup = "quest" | "pcvr" | "fbt"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateProfileFormSetup = {
  quest: "quest" as CreateProfileFormSetup,
  pcvr: "pcvr" as CreateProfileFormSetup,
  fbt: "fbt" as CreateProfileFormSetup,
}

export type CreateProfileFormRole = "sub" | "dom" | "switch"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateProfileFormRole = {
  sub: "sub" as CreateProfileFormRole,
  dom: "dom" as CreateProfileFormRole,
  switch: "switch" as CreateProfileFormRole,
}

export type CreateProfileFormGender = "male" | "maleTrans" | "female" | "femaleTrans" | "nonBinary"

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateProfileFormGender = {
  male: "male" as CreateProfileFormGender,
  maleTrans: "maleTrans" as CreateProfileFormGender,
  female: "female" as CreateProfileFormGender,
  femaleTrans: "femaleTrans" as CreateProfileFormGender,
  nonBinary: "nonBinary" as CreateProfileFormGender,
}

/**
 * Adds nested create feature
 */
export interface CreateProfileForm {
  femAvatar: boolean
  gender: CreateProfileFormGender
  trans: boolean
  furry: boolean
  mute: boolean
  role: CreateProfileFormRole
  setup: CreateProfileFormSetup
  birthMonth: number
  birthYear: number
  preferences: PreferencesForm
}
